CREATE TABLE SHIPWRECK(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR (255),
  DESCRIPTION VARCHAR (2000),
  `CONDITION` VARCHAR (255),
  DEPTH INT,
  LATITUDE DOUBLE,
  LONGITUDE DOUBLE,
  YEAR_DISCOVERED INT
)